### ISSUE TITLE
Buildcraft API included in the jar causes a crash

### ISSUE THREAD

**Issue by mrammy** [Dragon9815/PlayerInterfaceMod#2]
installing this with computronics installed and without buildcraft installed causes it to recognize the API and load its buildcraft related features even without it installed. It doesnt seem to be even used in your mod but it's included in the jar. Was that intentional?

**Comment by Dragon9815** [comment]
I need the log or the Crash-Report to process this any further-

**Comment by Dragon9815** [comment]
I tried it out on myself and it id fixed in the new version, 1.4.1.
